name: Update Profile README

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with Metrics
    runs-on: ubuntu-latest
    steps:
      # Usando a action do Athul, mas com a branch 'main'
      - uses: actions/checkout@v2
      - uses: athul/waka-readme-stats@main 
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.PAT }}
          SHOW_TITLE: "true"
          SHOW_TOTAL: "true"
          SHOW_MASKED_TIME: "false"
