name: Update Profile README

on:
  schedule:
    # Roda a cada 8 horas
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: athul/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.PAT }}

          # Opções da nova Action
          SHOW_TITLE: "true"
          SHOW_TOTAL: "true"
          SHOW_MASKED_TIME: "false"
