name: Update Profile README

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: Update README with WakaTime stats

    steps:
      - uses: actions/checkout@v3

      - name: Update WakaTime stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.PAT }}
          SECTION_NAME: "💻 WakaTime Stats"
          SHOW_EDITORS: "true"
          SHOW_OS: "false"
          SHOW_PROJECTS: "false"
          SHOW_TIMEZONE: "false"
